name: Deploy to Namecheap

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Enable manual execution
   inputs:
      version:
        description: 'Version number for production deployment'
        required: true

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Echo Version Number
        run: echo "Version number provided:${{ github.event.inputs.version }}"
      - name: Setup FTP environment
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.softvilla.website
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Adjust this to match the directory containing your static website files
          server-dir: //
          
